package main

import (
	"os"

	"github.com/Pmca96/API-Servers/UserService/routes"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"github.com/Pmca96/API-Servers/UserService/docs" // docs is generated by Swag CLI, you have to import it.
)

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

func main() {

	port := os.Getenv("PORT")

	if port == "" {
		port = "8080"
	}

	docs.SwaggerInfo_swagger.Title = "Swagger Example API"
	docs.SwaggerInfo_swagger.Description = "This is a sample server User server."
	docs.SwaggerInfo_swagger.Version = "1.0"
	docs.SwaggerInfo_swagger.Host = "localhost:" + port
	docs.SwaggerInfo_swagger.BasePath = ""
	docs.SwaggerInfo_swagger.Schemes = []string{"http", "https"}

	service := gin.New()

	service.Use(gin.Logger())

	service.Use(cors.Default())

	// Swagger
	// URL : swagger/index.html
	url := ginSwagger.URL("http://" + docs.SwaggerInfo_swagger.Host + "/swagger/doc.json") // The url pointing to API definition
	service.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	// Routes
	routes.AddRoutes(service)

	//this runs the server and allows it to listen to requests.
	service.Run(":" + port)
}
