package main

import (
	"UserServer/routes"
	"os"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"

	"UserServer/docs" // docs is generated by Swag CLI, you have to import it.
)

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

func main() {

	port := os.Getenv("PORT")

	if port == "" {
		port = "8000"
	}

	docs.SwaggerInfo_swagger.Title = "Swagger Example API"
	docs.SwaggerInfo_swagger.Description = "This is a sample server User server."
	docs.SwaggerInfo_swagger.Version = "1.0"
	docs.SwaggerInfo_swagger.Host = "user.swagger.io"
	docs.SwaggerInfo_swagger.BasePath = "/v2"
	docs.SwaggerInfo_swagger.Schemes = []string{"http", "https"}

	service := gin.New()
	service.Use(gin.Logger())

	service.Use(cors.Default())

	service.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	routes.AddRoutes(service)
	// these are the endpoints

	//this runs the server and allows it to listen to requests.
	service.Run(":" + port)
}
